token_filename: .token
include_private: False
ignore:
    owners:
        - akhagan
        - c-andy-martin
        - JMAStough
        - mothur
    languages:
        - HTML
        - CSS
        - TeX
