name: auto-update

on:
  schedule:
    - cron: '0 5 * * 1'

jobs:
  update:
    runs-on: 'macos-latest'
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: git-repos
           environment-file: config/environment.yml
           python-version: 3.7
           auto-activate-base: false
      - name: Update
        shell: bash -l {0}
        run: |
          snakemake --config token=${{ secrets.GH_ACCESS_TOKEN }}
          git add .
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
          git commit \
          --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
          -m '🤖 Auto-update' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
